# Generated by Django 5.2.4 on 2025-08-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requested_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('auditor', 'Auditor'), ('editor', 'Editor'), ('reader', 'Reader')], default='reader', max_length=20),
        ),
    ]
