# Generated by Django 5.2.4 on 2025-08-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_requested_editor_alter_profile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
