# Generated by Django 5.2.4 on 2025-08-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_avatar_alter_profile_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/profile/avatars/uknown-avatar.png', null=True, upload_to='users/profile/avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderador', 'Moderador'), ('editor', 'Editor'), ('reader', 'Reader')], default='reader', max_length=20),
        ),
    ]
